# Generated by Django 3.1.4 on 2020-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='note',
            field=models.CharField(default='', max_length=256),
        ),
    ]
