# Generated by Django 3.1.4 on 2020-12-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todos.status'),
        ),
    ]
