# Generated by Django 3.1.4 on 2020-12-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20201218_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todoList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.todolist'),
        ),
    ]
