# Generated by Django 3.1.4 on 2020-12-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20201218_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todoList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.todolist'),
            preserve_default=False,
        ),
    ]
