# Generated by Django 3.1.4 on 2020-12-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20201218_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='isSuccessful',
            field=models.BooleanField(default=False),
        ),
    ]
